FORMAT: 1A

# API設計課題

## フリマアプリAPI
本設計書で指定しているパラメータ及び、URLは仮のものである。

# Echo Hello [/items{?userId}]

## 商品一覧取得API [GET]

+ Parameters
    + userId: 4944 (number) - ユーザーID


+ Response 200 (application/json)
  レスポンスオブジェクト
  | パラメーター名 | 型           | 内容                |
  | :----------- | ------------ | -------------------|
  | `title`  | string           | 商品名       |
  | `makeAt` | string | 商品作成時間。ISO8601に基づいて表示 |
  | `id`  | number             |  商品ID       |
  | `category`  | string          |  カテゴリー名       |
  | `status`  | string        |  商品ステータス       |
  | `url`  | string            |  商品ページURL       |
  | `num`  | number            |   在庫数      |
  | `price`  | number |  1つ当たりの単価。〇〇円だが数字のみ返却      |
  | `description`  | string |  商品説明       |
  | `images`  | string |  商品画像があるURL       |

    + Attributes (object)
        + items()
            + title: プリンター (string) - 商品名
            + makeAt: 2015-05-05T12:30:00 (string) - 作成日時 (ISO8601 format)
            + id: 2345 (number) - 商品ID
            + category: electronics (string) - カテゴリー名
            + status: 発送待ち (string) - 商品ステータス 
            + url:https://ex.com/user/item/329801204 (string) - 商品ページURL
            + num: 20 (number) - 在庫数
            + price: 2000 (number) - 値段
            + description: 新古品です (string) - 商品説明
            + images: https://ex.com/user/item/329801204/images (string) - 商品画像URL